global using FlowerEcommerce.Application.Common.Constants;
global using FlowerEcommerce.Application.Interfaces.Services;
global using System.Security.Claims;
global using System.Text.Json;
global using FlowerEcommerce.Domain.Enums;
global using FlowerEcommerce.Application.Common.Models;
global using FlowerEcommerce.Domain.Constants;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;